auth.login=Login
auth.login_action=Login
auth.registration=Registration
auth.registration_action=Create account
auth.email=Email
auth.password=Password
auth.confirm_password=Confirm password
auth.or=Or
auth.continue_google=Continue with Google
auth.username=Username
auth.username_hint=your_username
auth.invalid_registration=User with this email already exists!
auth.invalid_login=Invalid email or password!
auth.error.username_empty=Username cannot be empty!
auth.error.username_length=Username must contain up to 6 characters!
auth.error.email_empty=Email cannot be empty!
auth.error.email_valid=Email is not valid!
auth.error.password_empty=Password cannot be empty!
auth.error.password_length=Password length must be 6-30 characters!
auth.error.password_english=Password must contain only english letters!
auth.error.password_lowercase=Password must contain at least one lowercase letter!
auth.error.password_uppercase=Password must contain at least one uppercase letter!
auth.error.password_digit=Password must contain at least one digit!
auth.error.password_special=Password must contain at least one special symbol!
auth.error.confirm_password_empty=Password confirm cannot be empty!
auth.error.confirm_password_match=Password do not match!
main_menu.login=\u0423\u0432\u0456\u0439\u0442\u0438
main_menu.login.in=Logging in...
main_menu.welcome.label=Welcome
menu.new_game=New Game
menu.load_game=Load Game
menu.settings=Settings
menu.exit=Exit
dialogue.history=History
dialogue.skip=Skip
dialogue.auto=Auto
dialogue.save=Save
dialogue.load=Load
dialogue.settings=Settings
