auth.login=Login
auth.login_action=Login
auth.registration=Registration
auth.registration_action=Create account
auth.email=Email
auth.password=Password
auth.confirm_password=Confirm password
auth.or=Or
auth.continue_google=Continue with Google
auth.username=Username
auth.username_hint=your_username
auth.invalid_registration=User with this email already exists!
auth.invalid_login=Invalid email or password!
auth.error.username_empty=Username cannot be empty!
auth.error.username_length=Username must contain up to 6 characters!
auth.error.email_empty=Email cannot be empty!
auth.error.email_valid=Email is not valid!
auth.error.password_empty=Password cannot be empty!
auth.error.password_length=Password length must be 6-30 characters!
auth.error.password_english=Password must contain only english letters!
auth.error.password_lowercase=Password must contain at least one lowercase letter!
auth.error.password_uppercase=Password must contain at least one uppercase letter!
auth.error.password_digit=Password must contain at least one digit!
auth.error.password_special=Password must contain at least one special symbol!
auth.error.confirm_password_empty=Password confirm cannot be empty!
auth.error.confirm_password_match=Password do not match!
main_menu.login=Login
main_menu.login.in=Logging in...
main_menu.welcome.label=Welcome
main_menu.default.name=Guest
main_menu.pictures.button=Pictures
main_menu.music.button=Music
main_menu.settings.button=Settings
main_menu.quit.button=Quit
main_menu.settings.top.label=Settings
main_menu.settings.game_options.label=Game options
main_menu.settings.music_volume.label=Music Volume
main_menu.settings.sound_volume.label=Sound Volume
main_menu.settings.display.label=Display
main_menu.settings.toggle.window.label=Windowed
main_menu.settings.toggle.fullscreen.label=Fullscreen
main_menu.settings.language.label=Language
main_menu.settings.apply.button=Apply
main_menu.warning.label=This game is not intended for the faint of heart.
menu.new_game=New Game
menu.load_game=Load Game
menu.settings=Settings
menu.exit=Exit
dialogue.history=History
dialogue.skip=Skip
dialogue.auto=Auto
dialogue.save=Save
dialogue.load=Load
dialogue.settings=Settings
