menu.new_game=New Game
menu.load_game=Load Game
menu.settings=Settings
menu.exit=Exit
dialogue.history=History
dialogue.skip=Skip
dialogue.auto=Auto
dialogue.save=Save
dialogue.load=Load
dialogue.settings=Settings


